micronaut:
  application:
    name: pix

  #datasources:
  #  default:
  #    url: jdbc:h2:mem:chave_pix;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
  #    driverClassName: org.h2.Driver
  #    username: sa
  #    password: ''
  #    schema-generate: CREATE_DROP
  #    dialect: H2
  #jpa.default.properties.hibernate.hbm2ddl.auto: update
  #jpa.default.properties.hibernate.show_sql: true
  #jpa.default.properties.hibernate.format_sql: false

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5434/chavepix`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: false
jpa.default.properties.hibernate.format_sql: false

#  docker run -p 5434:5432 --name db-chavepix -e POSTGRES_DB_USER=root -e POSTGRES_DB_PASS=root -e POSTGRES_DB_NAME=chavepix -d postgres

